server:
  port: 3344
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          #配置的github地址
          #uri: https://github.com/liaojiexin/springcloud-config-center.git
          #这里换成gitee地址，因为github经常连不上,记得公开，ssh的要配密钥
          uri: https://gitee.com/liaojiexin/springcloud-config-center.git
          #搜索目录
          search-paths:
            - springcloud-config-center
          #skip-ssl-validation: true
      #读取的分支
      label: master
  #rabbitmq配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #defaultZone: http://localhost:7001/eureka
      #加入eureka集群
      defaultZone: http://www.eureka7001.com:7001/eureka,http://www.eureka7002.com:7002/eureka

#rabbitmq相关配置
management:
  #暴露bus刷新配置的端点
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'
