server:
  port: 9527

spring:
  application:
    name: cloud-gateway-service
  cloud:
    gateway:
      #路由
      routes:
        - id: payment_routh  #payment_route #路由的ID，没有团定规则但要求唯一，建议配合服务名
          uri: http://localhost:8001 #瓜配后提供服务的路由地址
          predicates:
            - Path=/springcloud/payment/select/**  #断言，路经相匹配的进行路由
        - id: payment_routh2 #payment_route #路由的TD，没有固定规购但要求唯一，建议配合服务名
          uri: http://localhost:8001 #匹配后提供服务的路由地址
          predicates:
            - Path=/springcloud/payment/discovery/**  #断言，路经相匹配的进行路由

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #单机
      #defaultZone: http://localhost:7001/eureka
      #加入eureka集群
      defaultZone: http://www.eureka7001.com:7001/eureka,http://www.eureka7002.com:7002/eureka