server:
  port: 80

spring:
  application:
    # 这里的name是注册到eureka中的一个标志，写好后不要随便改，其他服务通过这个名称来找该服务
    name: cloud-order-server
  cloud:
    consul:
      port: 8500
      host: localhost
      discovery:
        service-name: ${spring.application.name}
