server:
  port: 8801

spring:
  application:
    name: cloud-stream-provider
  cloud:
    stream:
      #此处配置要绑定的rabbitmq的服务信息
      binders:
        #表示定义的名称，用于binding整合
        defaultRabbit:
          #消息组件类型
          type: rabbit
          #设置rabbitmq相关环境配置
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      #服务的整合处理
      bindings:
        #这个名字是一个通道的名称。生产者用output
        output:
          #表示要使用的Exchange名称定义
          destination: studyExchanger
          #设置消息类型，本次为json，文本则设置“text/plain”
          content-type: application/json
          #设置要绑定的消息服务的具体设置
          binder: defaultRabbit


eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #defaultZone: http://localhost:7001/eureka
      #加入eureka集群
      defaultZone: http://www.eureka7001.com:7001/eureka,http://www.eureka7002.com:7002/eureka