server:
  port: 8001

spring:
  application:
    # 这里的name是注册到eureka中的一个标志，写好后不要随便改，其他服务通过这个名称来找该服务
    name: cloud-payment-hystrix-service

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #单机
      #defaultZone: http://localhost:7001/eureka
      #加入eureka集群
      defaultZone: http://www.eureka7001.com:7001/eureka,http://www.eureka7002.com:7002/eureka
  instance:
    #配置web页面中显示的主机名
    instance-id: payment8001
    #访问路径可以显示ip地址
    prefer-ip-address: true
    #Eureka客户端向注册中心发送心跳的时间间隔,单位为秒，默认为30秒
    #lease-renewal-interval-in-seconds: 1
    #Eureak服务端在收到最后一次心跳后等待时间上限，单位为秒，默认为90秒，要大于lease-renewal-interval-in-seconds
    #lease-expiration-duration-in-seconds: 2
