server:
  port: 2001

spring:
  application:
    name: seata-order-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/springcloud2021?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 201314
  cloud:
    nacos:
      discovery:
        #nacos注册中心
        server-addr: localhost:8848

mybatis:
  mapperLocations: classpath:mapper/*.xml
  #统一实体类放在com.liaojiexin.entity下面，这样mapper.xml文件中的parameterType和resultType可以直接写实体类的名称，不用加上前面的com.liaojiexin.entity
  typeAliasesPackage: com.liaojiexin.springcloud.entity

management:
  endpoints:
    web:
      exposure:
        include: "*"

#seata:
#  application-id: ${spring.application.name}
#  # 这里的配置对应 seataServer.properties 中的 service.vgroupMapping.storage-service-group=default
#  enable-auto-data-source-proxy: false
##  config:
##    type: nacos
##    nacos:
##      server-addr: localhost:8848
##      username: nacos
##      password: nacos
##      # 微服务必须在一个组，否则服务发现不了，但Seata-server 可以在不同的组中
##      group: SEATA_GROUP
##      dataId: "seataServer.properties"
#  registry:
#    type: nacos
#    nacos:
#      application: seata-server
#      server-addr: localhost:8848
#      group: SEATA_GROUP
#      username: nacos
#      password: nacos
#      # 微服务必须在一个组，否则服务发现不了，但Seata-server 可以在不同的组中
#  service:
#    vgroup-mapping: seata-order-service-fescar-service-group