server:
  port: 7001

eureka:
  instance:
    hostname: www.eureka7001.com #eureka服务端的实例名称,这里去/etc/hosts里面配置，否则用localhost
  client:
    register-with-eureka: false     #false表示不向注册中心注册自己。
    fetch-registry: false     #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      #集群指向其它eureka
      defaultZone: http://www.eureka7002.com:7002/eureka/
      #单机就是指向自己
      #defaultZone: http://localhost:7001/eureka/
      #defaultZone: http://www.eureka7001.com:7002/eureka/
  server:
    #关闭自我保护机制，默认是打开的
    #enable-self-preservation: true
    #设置心跳超时时间，就剔除服务。即服务端每2秒检查一次是否有心跳，单位为毫秒
    #eviction-interval-timer-in-ms: 2000