server:
  port: 83
spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        #nacos注册中心
        #server-addr: localhost:8848
        #nginx代理集群的地址
        server-addr: localhost:8080
