server:
  port: 8401

spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        #nacos注册中心
        server-addr: localhost:8848
        #nginx代理集群的地址
        #server-addr: localhost:8080
    sentinel:
      transport:
        #Sentinel dashboard地址
        dashboard: localhost:84
        #通讯-监听，默认8719端口，假如端口被占用自动从8719依次+1扫描
        port: 8719
      #配置sentinel持久化数据源
      datasource:
        ds1:
          nacos:
            #nacos地址
            server-addr: localhost:8848
            dataId: ${spring.application.name}
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow

management:
  endpoints:
    web:
      exposure:
        include: "*"
