server:
  port: 2003

spring:
  application:
    name: seata-account-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/springcloud2021?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 201314
  cloud:
    nacos:
      discovery:
        #nacos注册中心
        server-addr: localhost:8848
        #nginx代理集群的地址
        #server-addr: localhost:8080

mybatis:
  mapperLocations: classpath:mapper/*.xml
  #统一实体类放在com.liaojiexin.entity下面，这样mapper.xml文件中的parameterType和resultType可以直接写实体类的名称，不用加上前面的com.liaojiexin.entity
  typeAliasesPackage: com.liaojiexin.springcloud.entity

management:
  endpoints:
    web:
      exposure:
        include: "*"